plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.nard.pro'
    compileSdk 34

    defaultConfig {
        applicationId "com.nard.pro"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
        resourceConfigurations += ["fa", "en"]
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix ".debug"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }

    packagingOptions {
        resources.excludes += ['META-INF/*.kotlin_module']
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.webkit:webkit:1.11.0'
}

/*
 *  فایل‌های اپ (پوشه‌ی www) را پیش از هر build داخل assets کپی می‌کند
 *  تا لازم نباشد دستی همگام‌شان کنید.
 */
tasks.register('syncWww', Copy) {
    from "${rootDir}/../www"
    into "${projectDir}/src/main/assets/www"
}
preBuild.dependsOn 'syncWww'
